// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Whisperer")>]
[<assembly: AssemblyProductAttribute("Whisperer")>]
[<assembly: AssemblyDescriptionAttribute("百度私信机器人")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Whisperer"
    let [<Literal>] AssemblyProduct = "Whisperer"
    let [<Literal>] AssemblyDescription = "百度私信机器人"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
